### PR TITLE
Final fixes for creation of v11 BLT unfolding files using CRAB 3.

### PR DESCRIPTION
**Pull request by jjacob**
Will confirm ready to merge once I submit CRAB jobs and they complete successfully.

### CODE REVIEW

**Comment by EmyrClement** [comment]
One thing I didn't do was set the input file paths to be "FileInPath".  At the moment, this runs on crab, but you have to change the input paths of the histograms to run locally.

**Comment by jjacob** [comment]
This pull request is now ready for checking; I have changed the lepton scale factor histogram files to use FileInPath.

**Comment by kreczko** [comment]
Generally it looks good.
If I had to change anything it would be:
- split this up into two pull requests: 
  1. CRAB3 configs
  2. Leptons scale factors
- put input files from CRAB 3 jobs into a separate file in python/Configurations (and add __init__.py) so it can be imported in the configs (it's python now!). That's 20 lines less per config.

**Comment by kreczko** [comment]
That should be it.
Once the 3 smaller pull requests are merged, rebase and see if there are any differences left.

**Comment by jjacob** [comment]
Closing this pull request as it was split into three separately merged pull requests (#125, #126 and #127).

**Pull request closed without merging**
