### PR TITLE
Update PseudoTopProducer

### PR DESCRIPTION
**Pull request by DouglasBurns**
Update pseudoTopProducer. This works with no Fatal Exceptions and should be fine to merge. I havent tested over a large sample or on different datasets yet.

### CODE REVIEW

**Comment by EmyrClement** [comment]
At the moment, we use genMET, which doesn't come from the pseudoTopProducer.  Is there now a suitable collection from the pseudoTopProducer?

Also, it would be good to at least run this over a few thousand events of the other generators.

**Comment by DouglasBurns** [comment]
Yes there is - in fact i was implementing it yesterday until lanas viva got
n the way

*________________________*


*Douglas Burns*
*PhD Student*

School of Physics            IIHE
University of Bristol          Vrije Universiteit Brussel
HH Wills Physics Lab      Building G
Tyndall Avenue                Pleinlaan 2
Bristol                              1050 Brussels
BS8 1TL

Douglas.Burns@bristol.ac.uk

**Comment by DouglasBurns** [comment]
Redesignated the old RecoMET producer so that it handles pseudoTopMETs. Now both GenMET and pseudoTopMET are stored in ntuple for comparison later. A quick glance shows the distributions match well.

**Comment by EmyrClement** [comment]
Good.  One last check - do you know how pseudoTopMET is proudced?  Is it 
the sum of all neutrinos (similar to genMET), or just neutrinos not from 
hadrons?  Or something different?

**Comment by DouglasBurns** [comment]
Theactual generation of the MET is hidden away in RIVET somewhere now. (Could access page in CMSSW git) Slide 13 on https://indico.cern.ch/event/610889/contributions/2463094/attachments/1412258/2160876/PseudoTopRivet.pdf states that it is the sum of all neutrinos a la GenMET

**Comment by EmyrClement** [comment]
If I'm on the right slide, slide 13 says:

ETmiss/Neutrinos: As an event level variable the missing transverse 
energy is calculated as the 4-vector sum of neutrinos from W/Z-boson 
decays. Tau decays are included. A neutrino is treated as a detectable 
particle and is selected for consideration in the same way as electrons 
or muons, i.e. the parent is required not to be a hadron or quark (u-b). 
(Expect that future sanitisation of generator record will remove the 
need for the quark requirement.)


So this isn't the same as genMET, which I think includes neutrinos from 
hadrons (not just from W/Z) ?

**Comment by DouglasBurns** [comment]
Yes correct slide. Ah ok.

**Pull request merged**
