### PR TITLE
Work on 74X

### PR DESCRIPTION
**Pull request by EmyrClement**
# 74X
## Electron VID
Implement the electron ID using the VID framework.  Functionality to remove/invert a cut is potentially available, but not implemented.  Apparently a nicer interface is coming soon.

## MET Uncertainties
Store MET Uncertainties

## Triggers for 74X MC samples
Update trigger paths to those that are likely to be used for 25ns running.

## B tag discriminator
The name of the CSV discriminator changed to "pfCombinedInclusiveSecondaryVertexV2BJetTags"

## Crab
Several new crab configs for 74X MC.  PHYS14 configs have been moved out of the way.
Submission scripts have been updated for these new samples.
Default file size for merging ntuples has been lowered to 2 GB

# Jets
The pt threshold for gen jets that are stored in the ntuples has been lowered to 20 GeV.  Slightly lower than the pt threshold of pf jets that we store, so there should now always be a match between a pf jet and a gen jet if needed.

Also, info on the parton associated with a jet (according to PAT) is stored.

### CODE REVIEW

**Comment by kreczko** [comment]
Could you please remove the *.out and *.err log files?
Probably worth adding these to .gitignore

**Comment by EmyrClement** [comment]
Done.  Thought I had removed them previously.

Also one other change, where I lowered the pt threshold of particle-level leptons that are stored in the ntuples.

**Comment by EmyrClement** [comment]
Was everything ok with this one?

**Comment by kreczko** [comment]
Yeah, for some reason I did not see the emails about the change.

**Pull request merged**
