### PR TITLE
Run II crab configs

### PR DESCRIPTION
**Pull request by DouglasBurns**
Added 25ns MiniAODv2 crab configs.
QCDMuEnriched600to800 is still 50ns.
Have not done different generator samples.

### CODE REVIEW

**Comment by kreczko** [comment]
Could you please merge ```3fbcae2``` and `4cb660e`?
```git rebase -i 3fbcae2^``` mark `4cb660e` as a fix and ```git push -f origin RunIIcrabConfigs```

**Comment by DouglasBurns** [comment]
Done

*________________________*


*Douglas Burns*
*PhD Student*

School of Physics
University of Bristol
HH Wills Physics Lab
University of Bristol
Tyndall Avenue
Bristol
BS8 1TL

 Douglas.Burns@bristol.ac.uk <John.Newby@bristol.ac.uk>

**Comment by kreczko** [comment]
so what is left to do is to resolve the conflicts ;)

**Comment by DouglasBurns** [comment]
Now done :)

**Pull request merged**
